config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :teams
  resources :team_members, only: [:create, :destroy, :index]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
}
  resources :users, only: [:show]
  resources :tasks do
    collection do
      get 'search'
    end
  end
  root 'tasks#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true, length: { maximum: 30 }
    validates :description, length: { maximum: 300 }
    validates :time_limit, presence: true
    validates :memo, length: { maximum: 200 }
    validate :time_limit_check
    enum importance: { 高: 1, 中: 2, 低: 3 }

    belongs_to :user
    belongs_to :team
    has_many :requests, dependent: :destroy
    accepts_nested_attributes_for :requests, allow_destroy: true, reject_if: :successor_blank

    def successor_blank(attributes)
        attributes[:successor_id].blank?
    end

    def time_limit_check
        errors.add(:time_limit, "は登録必須です。過去の日付は登録できません。") if self.time_limit == nil || (self.time_limit < DateTime.current)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_q, only: [:index, :search]

  # GET /tasks or /tasks.json
  def index
    @tasks = @q.result.order(:completion_flag).order(:time_limit).page(params[:page]).per(10)
    @time = Time.now()
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @requests = @task.requests.page(params[:page]).per(5)
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.requests.new
    @users = User.all
    @teams = Team.all
  end

  # GET /tasks/1/edit
  def edit
    @users = User.all
    @teams = Team.all
    @task.requests.build
    @task.requests.last.user_id = current_user.id if @task.requests.present?
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @teams = Team.all
    @users = User.all
    @task = current_user.tasks.build(task_params)
    @task.requests.last.user_id = current_user.id if @task.requests.present?

    respond_to do |format|
      if @task.save
        if @task.requests.length > 0
          RequestMailer.request_mail(@task).deliver
        end
        format.html { redirect_to task_url(@task), notice: "タスクを登録しました。" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @teams = Team.all
    @users = User.all
    # @task.requests.last.user_id = current_user.id if @task.requests.present? これがあると既存のリクエストの依頼者が書き変わってしまう
    @before_requests = @task.requests.length

      respond_to do |format|
      if @task.update(task_params)
        @after_requests = @task.requests.length
        if @after_requests > @before_requests
          RequestMailer.request_mail(@task).deliver
        end
        format.html { redirect_to task_url(@task), notice: "タスクを編集しました。" }
        format.json { render :show, status: :ok, location: @task }
      else
        @task.requests.build
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "タスクを削除しました。" }
      format.json { head :no_content }
    end
  end

  def search
    @results = @q.result.order(:completion_flag).order(:time_limit).page(params[:page]).per(10)
  end

  private

  def set_q
    @q = Task.ransack(params[:q])
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :time_limit, :importance, :completion_flag, :memo, :team_id,
                                                    requests_attributes: [:id, :message, :user_id, :successor_id])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form_edit.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "") %>  個のエラーが発生しています::</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="btn-cover">
  <div class="task-form">
    <h1>タスク編集  </h1>
    <div class="field">
      <%= form.label :タイトル %>
      <%= form.text_field :title, placeholder: "タイトルを入力（30文字以内）"  %>
    </div>

    <div class="field">
      <%= form.label :詳細 %>
      <%= form.text_area :description, placeholder: "詳細を入力（300文字以内）"  %>
    </div>

    <div class="field">
      <%= form.label :期日 %>
      <%= form.datetime_field :time_limit  %>
    </div>

    <div class="field">
      <%= form.label :重要度 %>
      <%= form.select :importance, Task.importances.keys, include_blank: "選択して下さい"  %>
    </div>

      <div class="field">
        <%= form.label :チーム %>
        <%= form.collection_select(:team_id, @teams, :id, :name)  %>
      </div>

      <div class="field">
        <%= form.label :メモ %>
        <%= form.text_area :memo, placeholder: "メモを入力（200文字以内）"  %>
      </div>

      <div class="field">
        <%= form.label :↓完了したらチェック%>
        <%= form.check_box :completion_flag %>
      </div>
    </div>

    <div>
      <%= form.fields_for :requests do |request| %>
        <% if request.index+1==task.requests.length %>
          <h2>申し送り事項 （<%= request.index+1 %>回目）</h2>
          <%= request.label  :メッセージ %>
          <%= request.text_area :message, placeholder: "メッセージを入力（200文字以内）" %>
          <%= request.hidden_field(:user_id, :value => current_user.id ) %>
          <%= request.label :後任者 %>
          <%= request.collection_select(:successor_id, @users, :id, :name, include_blank: "選択して下さい" ) %>
          <br>
          <br>
        <% end %>
      <% end %>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_form_new.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "") %> 個のエラーが発生しています:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="btn-cover">
  <div class="task-form">
    <h1>タスク登録</h1>
    <div class="field">
      <%= form.label :タイトル（※必須） %>
      <%= form.text_field :title, placeholder: "タイトルを入力（30文字以内）" %>
    </div>

    <div class="field">
      <%= form.label :詳細 %>
      <%= form.text_area :description, placeholder: "詳細を入力（300文字以内）"  %>
    </div>

    <div class="field">
      <%= form.label :期日（※必須） %>
      <%= form.datetime_field :time_limit  %>
    </div>

    <div class="field">
      <%= form.label :重要度 %>
      <%= form.select :importance, Task.importances.keys %>
    </div>

      <div class="field">
        <%= form.label :チーム（※必須） %>
        <%= form.collection_select(:team_id, @teams, :id, :name, include_blank: "選択して下さい" )  %>
      </div>

      <div class="field">
        <%= form.label :メモ %>
        <%= form.text_area :memo, placeholder: "メモを入力（200文字以内）"  %>
      </div>
    </div>

    <div>
      <%= form.fields_for :requests,@task.requests.build do |request| %>
        <h2>申し送りする （<%= request.index+1 %>回目）</h2>
        <%= request.label  :メッセージ %>
        <%= request.text_area :message, placeholder: "メッセージを入力（200文字以内）" %>
        <%= request.label :後任者（※必須） %>
        <%= request.collection_select(:successor_id, @users, :id, :name, include_blank: "選択して下さい" ) %>
        <br>
        <br>
      <% end %>
      <br>  <br>  <br>  <br>  <br>  <br> <br>  <br>  <br>  <br>
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="main-content">
    <%= render 'form_edit', task: @task %>
    <br><br>
    <%= button_to '詳細画面に戻る', @task, method: :get, class: "btn" %>
</div>

app/views/tasks/index.html.erb
<div class="main-content">

  <h1>タスク一覧</h1>
  <div class="btn-cover">
    <div class="search">
      <%= search_form_for @q, url: search_tasks_path do |f| %>
        <%= f.label :title_cont, '▽タスク名で検索' %>
        <%= f.search_field :title_cont, placeholder: "検索…" %>
        <%= f.submit '検索' %>
      <% end %>
    </div>

    <div class="search">
    <%= search_form_for @q, url: search_tasks_path do |f| %>
      <%= f.label :completion_flag, '▽状態で絞り込む' %>
      <%= f.radio_button :completion_flag_eq, 'true' %><span>完了</span>
      <%= f.radio_button :completion_flag_eq, 'false' %><span>未完了</span>
      <%= f.submit '絞り込む' %>
    <% end %>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>タイトル</th>
        <th>チーム</th>
        <th>担当者</th>
        <th><%= sort_link(@q, :time_limit, "期日") %></th>
        <th><%= sort_link(@q, :importance, "重要度") %></th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
    <% n = 0 %>
      <% @tasks.each do |task| %>
        <% if (task.completion_flag != true) && ((task.time_limit-@time).to_i < 87000) %>
          <tr  class="urgent">
        <% else %>
          <tr>
        <% end %>
          <div>
            <% if task.completion_flag == true %>
              <td class="completion done" >完　了</td>
            <% else %>
              <td class="completion">未完了</td>
            <% end %>
            <td class="index-title task_row" id="<%= "task_#{n}" %>"><%= task.title %></td>
            <td><%= task.team.name %></td>
            <td>
            <% if task.requests.length >0 %>
              <%=User.find(task.requests.last.successor_id).name %>
            <% else %>
              <%= task.user.name %>
            <% end %>
            </td>
              <% if (task.completion_flag != true) && ((task.time_limit-@time).to_i < 87000) %>
                <td class="urgent"  ><span class="urgent"><%= l task.time_limit %></span></td>
              <% else %>
                <td><%= l task.time_limit %></td>
              <% end %>
            </td>
            <td>
              <% if task.importance == "高" %>
                <span class="font high">
              <% elsif task.importance == "中" %>
                <span class="font normal">
              <% else %>
                <span class="font low">
              <% end %>
              <%= task.importance %>
              </span>
            </td>
            <td><%= button_to '詳細', task, method: :get, class: "btn mini-btn" %></td>
            <%if ((task.user.id == current_user.id) && (task.requests.length == 0 ))  || (task.requests.last&.successor_id == current_user.id)%>
              <td><%= button_to '編集', edit_task_path(task), method: :get, class: "btn mini-btn" %></td>
              <td><%= button_to '削除', task, method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "btn mini-btn" %></td>
            <% end %>
          </div>
        </tr>
        <% n += 1 %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @tasks %>

  <br>

<%# <%= button_to "タスクを登録する", {controller: "tasks", action: "new"}, {method: :get, class:"btn sign-btn " } %>
</div>

app/views/tasks/new.html.erb
<div class="main-content">
    <%= render 'form_new', task: @task %>
</div>

app/views/tasks/search.html.erb
<div class="main-content">
<h1>検索結果一覧</h1>


<table>
    <thead>
        <tr>
        <th></th>
        <th>タイトル</th>
        <th>チーム</th>
        <th>担当者</th>
        <th><%= sort_link(@q, :time_limit, "期日") %></th>
        <th><%= sort_link(@q, :importance, "重要度") %></th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @results.each do |task| %>
        <% if (task.completion_flag != true) && ((task.time_limit-Time.now).to_i < 1) %>
            <tr  class="urgent">
        <% else %>
            <tr>
        <% end %>
            <div>
            <% if task.completion_flag == true %>
                <td class="completion done" >完　了</td>
            <% else %>
                <td class="completion">未完了</td>
            <% end %>
            <td><%= task.title %></td>
            <td><%= task.team.name %></td>
            <td>
            <% if task.requests.length >0 %>
                <%=User.find(task.requests.last.successor_id).name %>
            <% else %>
                <%= task.user.name %>
            <% end %>
            </td>
                <% if (task.completion_flag != true) && ((task.time_limit-Time.now).to_i < 1) %>
                <td class="urgent"  ><span class="urgent"><%= l task.time_limit %></span></td>
                <% else %>
                <td><%= l task.time_limit %></td>
                <% end %>
            </td>
            <td>
                <% if task.importance == "高" %>
                <span class="font high">
                <% elsif task.importance == "中" %>
                <span class="font normal">
                <% else %>
                <span class="font low">
                <% end %>
                <%= task.importance %>
                </span>
            </td>
            <td><%= button_to '詳細', task, method: :get, class: "btn mini-btn" %></td>
            <%if ((task.user.id == current_user.id) && (task.requests.length == 0 ))  || (task.requests.last&.successor_id == current_user.id)%>
                <td><%= button_to '編集', edit_task_path(task), method: :get, class: "btn mini-btn" %></td>
                <td><%= button_to '削除', task, method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "btn mini-btn" %></td>
            <% end %>
            </div>
        </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @results %>
<br>

<%= button_to "タスク一覧に戻る", {controller: "tasks", action: "index"}, {method: :get, class:"btn" }  %>
</div>

app/views/tasks/show.html.erb
<div class="main-content">
  <div class="btn-cover">
    <div class="task-show">
      <h1><%= @task.title %></h1><br>

      <p>
        <strong>詳細:</strong>
        <%= @task.description %>
      </p>

      <p>
        <strong>期日:</strong>
        <% if (@task.completion_flag != true) && ((@task.time_limit-Time.now).to_i < 1) %>
          <span class="urgent"><%= l @task.time_limit %></span>
        <% else %>
          <%= l @task.time_limit %>
        <% end %>
      </p>

      <p>
        <strong>重要度:</strong>
        <% if @task.importance == "高" %>
          <span class="font high">
        <% elsif @task.importance == "中" %>
          <span class="font normal">
        <% else %>
          <span class="font low">
        <% end %>
        <%= @task.importance %>
        </span>
      </p>

      <p>
        <strong>進捗:</strong>
        <% if @task.completion_flag == true %>
        <span class="font done">完了</span>
        <% else %>
        <span class="font Incomplete">未完了</span>
        <% end %>
      </p>

      <p>
        <strong>メモ:</strong>
        <%= @task.memo %>
      </p>

      <p>
        <strong>チーム:</strong>
        <%= @task.team.name %>
      </p>

      <p>
        <strong>投稿者:</strong>
        <%= @task.user.name %>
      </p>
      <br>
      <div class="btn-cover">
        <% if ((@task.user.id == current_user.id) && (@task.requests.length == 0 ))  || (@task.requests.last&.successor_id == current_user.id)%>
          <%= button_to '編集', edit_task_path(@task), {method: :get, class:"btn" }%>
          <%= button_to '削除', @task, method: :delete, data: { confirm: '削除してもよろしいですか?' }, class:"btn" %>
        <% end %>
        <%= button_to "戻る", {controller: "tasks", action: "index"}, {method: :get, class:"btn" } %>
      </div>
    </div>

    <div class="request-show">
      <% if @task.requests.count > 0 %>
        <h2>申し送り履歴</h2>
        <table>
          <thead>
            <tr>
              <th></th>
              <th>メッセージ</th>
              <th>前任者</th>
              <th>後任者</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% x=1 %>
            <% @requests.each do |request| %>
            <tr>
              <td><%= x %>回目</td>
              <td class="request-msg"><%= request.message %></td>
              <td><%= User.find(request.user_id).name %></td>
              <td><%= User.find(request.successor_id).name %></td>
              <% x+=1 %>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @requests %>
      <% end %>
    </div>

  </div>
</div>