config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :teams
  resources :team_members, only: [:create, :destroy, :index]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
}
  resources :users, only: [:show]
  resources :tasks do
    collection do
      get 'search'
    end
  end
  root 'tasks#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :requests
  has_many :team_members, dependent: :destroy
  has_many :team_member_teams, through: :team_members, source: :team

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲスト"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'guest_admin@example.com') do |user|
      user.name = "ゲスト（アドミン）"
      user.password = SecureRandom.urlsafe_base64
      user.admin = true
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  protected
  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def guest_admin_sign_in
    user = User.guest_admin
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザー（管理者）としてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    if (current_user.admin == true) || (current_user.id == @user.id)
      @teams = @user.team_member_teams.page(params[:page]).per(6)
      tasks = Task.all.order(:completion_flag).order(:time_limit)
      user_tasks = []
      tasks.each do |task|
        if ((task.user.id == @user.id) && (task.requests.length == 0 ))  || (task.requests.last&.successor_id == @user.id)
          user_tasks.push(task)
        end
      end
      @user_tasks = Kaminari.paginate_array(user_tasks).page(params[:page]).per(5)
    else
      redirect_to tasks_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="main-content">
    <div class="btn-cover">
        <div>
            <h1><%= @user.name %>のページ</h1>
            <p>メールアドレス : <%= @user.email %></p>
        </div>
        <div>
            <%if @user.admin == true%>
                <%= button_to '管理者ページへ行く', rails_admin_path, method: :get, class: "btn admin-btn" %>
            <% end %>
        </div>
    </div>
    <br>

    <div class="btn-cover">
        <div class="team-show">
        <table>
            <thead>
                <h3>所属チーム</h3>
            </thead>
            <tbody>
                <% @teams.each do |team| %>
                    <tr>
                        <td><%= team.name %></td>
                        <td><%= button_to '詳細',  team_path(id: team.id),method: :get, class: "btn mini-btn" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= paginate @teams %>
    </div>

        <div>
            <table>
                <thead>
                    <h3><%= @user.name %>のタスク一覧</h3>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>タイトル</th>
                        <th>チーム</th>
                        <th>期日</th>
                        <th>重要度</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @user_tasks.each do |task| %>
                        <%# <% if ((task.user.id == @user.id) && (task.requests.length == 0 ))  || (task.requests.last&.successor_id == @user.id)%>
                            <% if (task.completion_flag != true) && ((task.time_limit-Time.now).to_i < 87000) %>
                                <tr  class="urgent">
                            <% else %>
                                <tr>
                            <% end %>
                            <div>
                            <% if task.requests.length != 0 %>
                                <td class="request"><span class="request">申送</span></td>
                            <% else %>
                                <td class="request"><span>        </span></td>
                            <% end %>
                            <% if task.completion_flag == true %>
                                <td class="completion done" >完　了</td>
                            <% else %>
                                <td class="completion">未完了</td>
                            <% end %>
                            <td><%= task.title %></td>
                            <td><%= task.team.name %></td>
                                <% if (task.completion_flag != true) && ((task.time_limit-Time.now).to_i < 87000) %>
                                    <td class="urgent"  ><span class="urgent"><%= l task.time_limit %></span></td>
                                <% else %>
                                    <td><%= l task.time_limit %></td>
                                <% end %>
                            <td>
                                <% if task.importance == "高" %>
                                    <span class="font high">
                                <% elsif task.importance == "中" %>
                                    <span class="font normal">
                                <% else %>
                                    <span class="font low">
                                <% end %>
                                <%= task.importance %>
                                </span>
                            </td>
                            <td><%= button_to '詳細', task, method: :get, class: "btn mini-btn" %></td>
                            <% if ((task.user.id == @user.id) && (task.requests.length == 0 ))  || (task.requests.last&.successor_id == @user.id)%>
                                <td><%= button_to '編集', edit_task_path(task), method: :get, class: "btn mini-btn" %></td>
                                <td><%= button_to '削除', task, method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "btn mini-btn" %></td>
                            <% end %>
                            </div>
                        </tr>
                        <% end %>
                    <%# <% end %>
                </tbody>
            </table>
            <%= paginate @user_tasks %>
        </div>
    </div>

</div>